from grafos import Estado, Accion


class Datos:
    accN = Accion('N')
    accS = Accion('S')
    accE = Accion('E')
    accO = Accion('O')
    accNE = Accion('NE')
    accNO = Accion('NO')
    accSE = Accion('SE')
    accSO = Accion('SO')

    manizales = Estado('Manizales', [accN])
    medellin = Estado('Medellin', [accS, accNO, accNE])
    santafe = Estado('Santa Fe', [accNO, accSE])
    dabeiba = Estado('Dabeiba', [accNO, accSE])
    chigorodo = Estado('Chigorodo', [accN, accSE])
    arboletes = Estado('Arboletes', [accS, accE])
    barbosa = Estado('Barbosa', [accSO, accNE, accNO])
    yarumal = Estado('Yarumal', [accSE, accNE, accE])
    cisneros = Estado('Cisneros', [accSO, accE])
    amalfi = Estado('Amalfi', [accO, accE])
    maceo = Estado('Maceo', [accO, accN])
    remedios = Estado('Remedios', [accNO, accO, accS])
    caucasia = Estado('Caucasia', [accNO, accSE, accSO])
    monteria = Estado('Monteria', [accO, accNE, accSE])
    planetarica = Estado('Planeta Rica', [accNO, accN, accSE])
    sahagun = Estado('Sahagun', [accSO, accS, accN])
    cienaga = Estado('Cienaga', [accO, accNE])
    cerete = Estado('Cerete', [accE, accN])
    covenias = Estado('Coveñas', [accS, accNE])
    sincelejo = Estado('Sincelejo', [accNO, accS])
    tolu = Estado('Tolu', [accSO, accSE])

    acciones = {
        'Manizales': {'N': medellin},
        'Medellin': {'S': manizales, 'NO': santafe, 'NE': barbosa},
        'Santa Fe': {'NO': dabeiba, 'SE': medellin},
        'Dabeiba': {'NO': chigorodo, 'SE': santafe},
        'Chigorodo': {'N': arboletes, 'SE': dabeiba},
        'Arboletes': {'S': chigorodo, 'E': monteria},
        'Barbosa': {'NO': yarumal, 'SO': medellin, 'NE': cisneros},
        'Yarumal': {'SE': barbosa, 'NE': caucasia, 'E': amalfi},
        'Cisneros': {'SO': barbosa, 'E': maceo},
        'Amalfi': {'O': yarumal, 'E': remedios},
        'Maceo': {'O': cisneros, 'N': remedios},
        'Remedios': {'NO': caucasia, 'O': amalfi, 'S': maceo},
        'Caucasia': {'NO': planetarica, 'SE': remedios, 'SO': yarumal},
        'Monteria': {'O': arboletes, 'NE': cerete, 'SE': planetarica},
        'Planeta Rica': {'NO': monteria, 'N': sahagun, 'SE': caucasia},
        'Sahagun': {'SO': cienaga, 'S': planetarica, 'N': sincelejo},
        'Cienaga': {'O': cerete, 'NE': sahagun},
        'Cerete': {'E': cienaga, 'N': covenias},
        'Coveñas': {'S': cerete, 'NE': tolu},
        'Sincelejo': {'NO': tolu, 'S': sahagun},
        'Tolu': {'SO': covenias, 'SE': sincelejo}
    }

    costos = {
        'Manizales': {'N': 228},
        'Medellin': {'S': 228, 'NO': 56, 'NE': 44},
        'Santa Fe': {'NO': 103, 'SE': 56},
        'Dabeiba': {'NO': 109, 'SE': 103},
        'Chigorodo': {'N': 177, 'SE': 109},
        'Arboletes': {'S': 177, 'E': 69},
        'Barbosa': {'NO': 99, 'SO': 44, 'NE': 38},
        'Yarumal': {'SE': 99, 'NE': 161, 'E': 157},
        'Cisneros': {'SO': 38, 'E': 48},
        'Amalfi': {'O': 157, 'E': 83},
        'Maceo': {'O': 48, 'N': 83},
        'Remedios': {'NO': 148, 'O': 83, 'S': 83},
        'Caucasia': {'NO': 70, 'SE': 148, 'SO': 161},
        'Monteria': {'O': 69, 'NE': 23, 'SE': 54},
        'Planeta Rica': {'NO': 54, 'N': 73, 'SE': 70},
        'Sahagun': {'SO': 34, 'S': 73, 'N': 48},
        'Cienaga': {'O': 19, 'NE': 34},
        'Cerete': {'E': 19, 'N': 73},
        'Coveñas': {'S': 73, 'NE': 22},
        'Sincelejo': {'NO': 40, 'S': 48},
        'Tolu': {'SO': 22, 'SE': 40}
    }

    heuristicas = {
        'Manizales': {
            'Manizales': 0,
            'Medellin': 152,
            'Santa Fe': 236,
            'Dabeiba': 324,
            'Chigorodo': 396,
            'Arboletes': 547,
            'Monteria':  654,
            'Barbosa': 215,
            'Yarumal': 363,
            'Cisneros': 247,
            'Amalfi': 598,
            'Maceo': 288,
            'Remedios': 359,
            'Caucasia': 457,
            'Planeta Rica': 503,
            'Sahagun': 612,
            'Cienaga': 642,
            'Cerete': 689,
            'Coveñas': 738,
            'Sincelejo': 645,
            'Tolu': 679,
        },
        'Medellin': {
            'Manizales': 152,
            'Medellin': 0,
            'Santa Fe': 84,
            'Dabeiba': 172,
            'Chigorodo': 245,
            'Arboletes': 397,
            'Monteria': 502,
            'Barbosa': 63,
            'Yarumal': 211,
            'Cisneros': 95,
            'Amalfi': 446,
            'Maceo': 136,
            'Remedios': 207,
            'Caucasia': 305,
            'Planeta Rica': 351,
            'Sahagun': 461,
            'Cienaga': 490,
            'Cerete': 537,
            'Coveñas': 586,
            'Sincelejo': 493,
            'Tolu': 605,
        },
        'Santa Fe': {
            'Manizales': 236,
            'Medellin': 84,
            'Santa Fe': 0,
            'Dabeiba': 88,
            'Chigorodo': 161,
            'Arboletes': 313,
            'Monteria': 418,
            'Barbosa': 147,
            'Yarumal': 295,
            'Cisneros': 179,
            'Amalfi': 530,
            'Maceo': 220,
            'Remedios': 291,
            'Caucasia': 389,
            'Planeta Rica': 435,
            'Sahagun': 545,
            'Cienaga': 406,
            'Cerete': 453,
            'Coveñas': 502,
            'Sincelejo': 577,
            'Tolu': 521,
        },
        'Dabeiba': {
            'Manizales': 324,
            'Medellin': 172,
            'Santa Fe': 88,
            'Dabeiba': 0,
            'Chigorodo': 73,
            'Arboletes': 225,
            'Monteria': 330,
            'Barbosa': 235,
            'Yarumal': 383,
            'Cisneros': 267,
            'Amalfi': 618,
            'Maceo': 308,
            'Remedios': 379,
            'Caucasia': 477,
            'Planeta Rica': 523,
            'Sahagun': 633,
            'Cienaga': 494,
            'Cerete': 365,
            'Coveñas': 414,
            'Sincelejo': 455,
            'Tolu': 433,
        },
        'Chigorodo': {
            'Manizales': 397,
            'Medellin': 245,
            'Santa Fe': 161,
            'Dabeiba': 73,
            'Chigorodo': 0,
            'Arboletes': 152,
            'Monteria': 257,
            'Barbosa': 308,
            'Yarumal': 456,
            'Cisneros': 340,
            'Amalfi': 691,
            'Maceo': 381,
            'Remedios': 452,
            'Caucasia': 550,
            'Planeta Rica': 633,
            'Sahagun': 350,
            'Cienaga': 567,
            'Cerete': 292,
            'Coveñas': 341,
            'Sincelejo': 382,
            'Tolu': 360,
        },
        'Arboletes': {
            'Manizales': 549,
            'Medellin': 397,
            'Santa Fe': 313,
            'Dabeiba': 198,
            'Chigorodo': 152,
            'Arboletes': 0,
            'Monteria': 105,
            'Barbosa': 460,
            'Yarumal': 645,
            'Cisneros': 492,
            'Amalfi': 410,
            'Maceo': 366,
            'Remedios': 295,
            'Caucasia': 197,
            'Planeta Rica': 151,
            'Sahagun': 198,
            'Cienaga': 415,
            'Cerete': 140,
            'Coveñas': 189,
            'Sincelejo': 230,
            'Tolu': 208,
        },
        'Monteria': {
            'Manizales': 654,
            'Medellin': 502,
            'Santa Fe': 418,
            'Dabeiba': 303,
            'Chigorodo': 257,
            'Arboletes': 105,
            'Monteria': 0,
            'Barbosa': 378,
            'Yarumal': 230,
            'Cisneros': 597,
            'Amalfi': 305,
            'Maceo': 491,
            'Remedios': 400,
            'Caucasia': 92,
            'Planeta Rica': 46,
            'Sahagun': 58,
            'Cienaga': 64,
            'Cerete': 35,
            'Coveñas': 84,
            'Sincelejo': 90,
            'Tolu': 103,
        },
        'Barbosa': {
            'Manizales': 215,
            'Medellin': 63,
            'Santa Fe': 147,
            'Dabeiba': 308,
            'Chigorodo': 460,
            'Arboletes': 460,
            'Monteria': 565,
            'Barbosa': 0,
            'Yarumal': 148,
            'Cisneros': 32,
            'Amalfi': 383,
            'Maceo': 73,
            'Remedios': 144,
            'Caucasia': 242,
            'Planeta Rica': 332,
            'Sahagun': 442,
            'Cienaga': 471,
            'Cerete': 600,
            'Coveñas': 649,
            'Sincelejo': 474,
            'Tolu': 668,
        },
        'Yarumal': {
            'Manizales': 363,
            'Medellin': 211,
            'Santa Fe': 295,
            'Dabeiba': 383,
            'Chigorodo': 456,
            'Arboletes': 608,
            'Monteria': 713,
            'Barbosa': 148,
            'Yarumal': 0,
            'Cisneros': 180,
            'Amalfi': 235,
            'Maceo': 421,
            'Remedios': 350,
            'Caucasia': 138,
            'Planeta Rica': 184,
            'Sahagun': 294,
            'Cienaga': 323,
            'Cerete': 265,
            'Coveñas': 314,
            'Sincelejo': 326,
            'Tolu': 360,
        },
        'Cisneros': {
            'Manizales': 288,
            'Medellin': 136,
            'Santa Fe': 220,
            'Dabeiba': 308,
            'Chigorodo': 381,
            'Arboletes': 533,
            'Monteria': 302,
            'Barbosa': 32,
            'Yarumal': 180,
            'Cisneros': 0,
            'Amalfi': 227,
            'Maceo': 41,
            'Remedios': 112,
            'Caucasia': 210,
            'Planeta Rica': 256,
            'Sahagun': 366,
            'Cienaga': 395,
            'Cerete': 291,
            'Coveñas': 340,
            'Sincelejo': 398,
            'Tolu': 432,
        },
        'Amalfi': {
            'Manizales': 598,
            'Medellin': 446,
            'Santa Fe': 530,
            'Dabeiba': 618,
            'Chigorodo': 562,
            'Arboletes': 410,
            'Monteria': 305,
            'Barbosa': 383,
            'Yarumal': 235,
            'Cisneros': 227,
            'Amalfi': 0,
            'Maceo': 186,
            'Remedios': 115,
            'Caucasia': 213,
            'Planeta Rica': 259,
            'Sahagun': 369,
            'Cienaga': 398,
            'Cerete': 340,
            'Coveñas': 389,
            'Sincelejo': 401,
            'Tolu': 435,
        },
        'Maceo': {
            'Manizales': 288,
            'Medellin': 136,
            'Santa Fe': 220,
            'Dabeiba': 308,
            'Chigorodo': 381,
            'Arboletes': 533,
            'Monteria': 261,
            'Barbosa': 73,
            'Yarumal': 421,
            'Cisneros': 41,
            'Amalfi': 186,
            'Maceo': 0,
            'Remedios': 71,
            'Caucasia': 169,
            'Planeta Rica': 215,
            'Sahagun': 325,
            'Cienaga': 354,
            'Cerete': 296,
            'Coveñas': 345,
            'Sincelejo': 357,
            'Tolu': 364,
        },
        'Remedios': {
            'Manizales': 359,
            'Medellin': 207,
            'Santa Fe': 291,
            'Dabeiba': 379,
            'Chigorodo': 452,
            'Arboletes': 604,
            'Monteria': 709,
            'Barbosa': 144,
            'Yarumal': 350,
            'Cisneros': 112,
            'Amalfi': 115,
            'Maceo': 71,
            'Remedios': 0,
            'Caucasia': 98,
            'Planeta Rica': 144,
            'Sahagun': 254,
            'Cienaga': 283,
            'Cerete': 225,
            'Coveñas': 274,
            'Sincelejo': 286,
            'Tolu': 293,
        },
        'Caucasia': {
            'Manizales': 501,
            'Medellin': 349,
            'Santa Fe': 433,
            'Dabeiba': 521,
            'Chigorodo': 594,
            'Arboletes': 197,
            'Monteria': 92,
            'Barbosa': 242,
            'Yarumal': 138,
            'Cisneros': 210,
            'Amalfi': 213,
            'Maceo': 169,
            'Remedios': 98,
            'Caucasia': 0,
            'Planeta Rica': 46,
            'Sahagun': 156,
            'Cienaga': 185,
            'Cerete': 127,
            'Coveñas': 176,
            'Sincelejo': 188,
            'Tolu': 195,
        },
        'Planeta Rica': {
            'Manizales': 547,
            'Medellin': 395,
            'Santa Fe': 479,
            'Dabeiba': 376,
            'Chigorodo': 303,
            'Arboletes': 151,
            'Barbosa': 332,
            'Yarumal': 184,
            'Cisneros': 256,
            'Amalfi': 259,
            'Maceo': 215,
            'Remedios': 144,
            'Caucasia': 46,
            'Planeta Rica': 0,
            'Sahagun': 110,
            'Cienaga': 139,
            'Cerete': 81,
            'Coveñas': 130,
            'Sincelejo': 142,
            'Tolu': 176,
        },
        'Sahagun': {
            'Manizales': 657,
            'Medellin': 505,
            'Santa Fe': 589,
            'Dabeiba': 677,
            'Chigorodo': 350,
            'Arboletes': 198,
            'Monteria': 93,
            'Barbosa': 442,
            'Yarumal': 294,
            'Cisneros': 366,
            'Amalfi': 369,
            'Maceo': 325,
            'Remedios': 254,
            'Caucasia': 156,
            'Planeta Rica': 110,
            'Sahagun': 0,
            'Cienaga': 29,
            'Cerete': 58,
            'Coveñas': 107,
            'Sincelejo': 32,
            'Tolu': 66,
        },
        'Cienaga': {
            'Manizales': 686,
            'Medellin': 505,
            'Santa Fe': 589,
            'Dabeiba': 394,
            'Chigorodo': 321,
            'Arboletes': 169,
            'Monteria': 64,
            'Barbosa': 442,
            'Yarumal': 294,
            'Cisneros': 474,
            'Amalfi': 529,
            'Maceo': 354,
            'Remedios': 283,
            'Caucasia': 185,
            'Planeta Rica': 139,
            'Sahagun': 29,
            'Cienaga': 0,
            'Cerete': 29,
            'Coveñas': 78,
            'Sincelejo': 61,
            'Tolu': 97,
        },
        'Cerete': {
            'Manizales': 628,
            'Medellin': 476,
            'Santa Fe': 560,
            'Dabeiba': 365,
            'Chigorodo': 292,
            'Arboletes': 240,
            'Monteria': 35,
            'Barbosa': 413,
            'Yarumal': 265,
            'Cisneros': 297,
            'Amalfi': 340,
            'Maceo': 296,
            'Remedios': 225,
            'Caucasia': 127,
            'Planeta Rica': 81,
            'Sahagun': 93,
            'Cienaga': 29,
            'Cerete': 0,
            'Coveñas': 49,
            'Sincelejo': 90,
            'Tolu': 103,
        },
        'Coveñas': {
            'Manizales': 677,
            'Medellin': 525,
            'Santa Fe': 441,
            'Dabeiba': 414,
            'Chigorodo': 341,
            'Arboletes': 189,
            'Monteria': 79,
            'Barbosa': 462,
            'Yarumal': 314,
            'Cisneros': 386,
            'Amalfi': 389,
            'Maceo': 345,
            'Remedios': 274,
            'Caucasia': 176,
            'Planeta Rica': 130,
            'Sahagun': 134,
            'Cienaga': 69,
            'Cerete': 49,
            'Coveñas': 0,
            'Sincelejo': 53,
            'Tolu': 19,
        },
        'Sincelejo': {
            'Manizales': 645,
            'Medellin': 493,
            'Santa Fe': 577,
            'Dabeiba': 455,
            'Chigorodo': 382,
            'Arboletes': 230,
            'Monteria': 125,
            'Barbosa': 474,
            'Yarumal': 326,
            'Cisneros': 506,
            'Amalfi': 741,
            'Maceo': 357,
            'Remedios': 286,
            'Caucasia': 188,
            'Planeta Rica': 142,
            'Sahagun': 32,
            'Cienaga': 61,
            'Cerete': 90,
            'Coveñas': 53,
            'Sincelejo': 0,
            'Tolu': 34,
        },
        'Tolu': {
            'Manizales': 679,
            'Medellin': 527,
            'Santa Fe': 517,
            'Dabeiba': 433,
            'Chigorodo': 360,
            'Arboletes': 208,
            'Monteria': 103,
            'Barbosa': 508,
            'Yarumal': 360,
            'Cisneros': 540,
            'Amalfi': 435,
            'Maceo': 391,
            'Remedios': 320,
            'Caucasia': 222,
            'Planeta Rica': 176,
            'Sahagun': 66,
            'Cienaga': 95,
            'Cerete': 68,
            'Coveñas': 19,
            'Sincelejo': 34,
            'Tolu': 0,
        },
    }
